CMAKE_MINIMUM_REQUIRED(VERSION 3.2 FATAL_ERROR)

FUNCTION(BUILD_PSIMD)
  INCLUDE(ExternalProject)
  ExternalProject_Add(psimd
    GIT_REPOSITORY https://github.com/Maratyszcza/psimd.git
    GIT_TAG master
    INSTALL_COMMAND ""
    BUILD_BYPRODUCTS <SOURCE_DIR>/include/psimd.h
  )

  ExternalProject_Get_Property(psimd source_dir)
  SET(PSIMD_FOUND TRUE PARENT_SCOPE)
  SET(PSIMD_DEPENDENCY psimd PARENT_SCOPE)
  SET(PSIMD_INCLUDE_DIRS ${source_dir}/include PARENT_SCOPE)

  MARK_AS_ADVANCED(FORCE PSIMD_FOUND)
  MARK_AS_ADVANCED(FORCE PSIMD_DEPENDENCY)
  MARK_AS_ADVANCED(FORCE PSIMD_INCLUDE_DIRS)
ENDFUNCTION(BUILD_PSIMD)

BUILD_PSIMD()
