CMAKE_MINIMUM_REQUIRED(VERSION 3.2 FATAL_ERROR)

FUNCTION(BUILD_FXDIV)
  INCLUDE(ExternalProject)
  SET(FXDIV_BUILD_TESTS OFF CACHE BOOL "")
  SET(FXDIV_BUILD_BENCHMARKS OFF CACHE BOOL "")
  ExternalProject_Add(fxdiv
    GIT_REPOSITORY https://github.com/Maratyszcza/FXdiv.git
    GIT_TAG master
    INSTALL_COMMAND ""
    BUILD_BYPRODUCTS <SOURCE_DIR>/include/fxdiv.h
  )

  ExternalProject_Get_Property(fxdiv source_dir)
  SET(FXDIV_FOUND TRUE PARENT_SCOPE)
  SET(FXDIV_DEPENDENCY fxdiv PARENT_SCOPE)
  SET(FXDIV_INCLUDE_DIRS ${source_dir}/include PARENT_SCOPE)

  MARK_AS_ADVANCED(FORCE FXDIV_FOUND)
  MARK_AS_ADVANCED(FORCE FXDIV_DEPENDENCY)
  MARK_AS_ADVANCED(FORCE FXDIV_INCLUDE_DIRS)
ENDFUNCTION(BUILD_FXDIV)

BUILD_FXDIV()
